version: '3'

services:
  products-db:
    container_name: products-database
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=lgcholoquinga
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=productsdb